### ISSUE TITLE
[FPWD request] FPWD for Resource Timing L2

### ISSUE THREAD

**Issue by siusin** [plehegar/transitions#4]
# Document title, URLs, estimated publication date

Resource Timing Level 2
https://www.w3.org/TR/2016/WD-resource-timing-2-20161103/
https://www.w3.org/TR/resource-timing-2/
03 November 2016

# Abstract

This specification defines an interface for web applications to access the complete timing information for resources in a document.

# Status

Resource Timing Level 2 replaces the first version of Resource Timing [RESOURCE-TIMING].

This specification is ready for wide review, with the following features at risk for the first release:

	• Dependency with Performance Timeline 2, since performance observers are lacking implementations;
	• Dependency with High Resolution Time 2 and workers support, including workerStart, since we're still refining time origin;
	• nextHopProtocol, transferSize, encodedBodySize, and decodedBodySize, since we're currently lacking implementations;
	• Surfacing failed fetches in the timeline;
	• secureConnectionStart as a required attribute.
This document was published by the Web Performance Working Group as a First Public Working Draft. This document is intended to become a W3C Recommendation. If you wish to make comments regarding this document, please send them to public-web-perf@w3.org (subscribe, archives) with [resource-timing-2] at the start of your email's subject. All comments are welcome.

Publication as a First Public Working Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

This document was produced by a group operating under the 5 February 2004 W3C Patent Policy. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.

This document is governed by the 1 September 2015 W3C Process Document.

# Is it a delta specification intended to become a W3C Recommendation?

Nope.

# Link to group's decision to request transition

https://www.w3.org/2016/10/26-webperf-minutes.html
… recorded the group’s consensus on publishing a FPWD for Resource Timing L2, with no objection.

# Information about implementations known to the Working Group

https://github.com/w3c/resource-timing/issues/71
The following features at risk were removed from L1 for lack of implementations or lack of consensus: workerStart, nextHopProtocol, transferSize, encodedBodySize, and decodedBodySize.
Now we have full implementation in Firefox, and partial implementation in Chrome and Edge.

**Comment by plehegar** [comment]
published
