### ISSUE TITLE
[FPWD request] Pointer Lock 2.0

### ISSUE THREAD

**Issue by siusin** [plehegar/transitions#6]
# Document title, URLs, estimated publication date
Pointer Lock 2.0
https://www.w3.org/TR/2016/WD-pointerlock-2-20161122/
22 November 2016

# Abstract
This specification defines an API that provides scripted access to raw mouse movement data while locking the target of mouse events to a single element and removing the cursor from view. This is an essential input mode for certain classes of applications, especially first person perspective 3D applications and 3D modeling software.

# Status
See https://www.w3.org/TR/2016/WD-pointerlock-2-20161122/#sotd.
[[ ...
Summary of changes since W3C Recommendation 27 October 2016:
Shadow DOM accomodating changes. Document.pointerLockElement split into Document.pointerLockElement and ShadowRoot.pointerLockElement. References to document replaced with Shadow DOM-aware vocabulary such as 'shadow-including root'.
]]

# Is it a delta specification intended to become a W3C Recommendation?
No.

# Link to group's decision to request transition
https://github.com/w3c/pointerlock/issues/12
and https://lists.w3.org/Archives/Public/public-webapps/2016OctDec/0029.html

# Information about implementations known to the Working Group
The Shadow DOM accomodating changes are getting implemented. Tests for these changes have been added to the w3c/web-platform-tests project.

**Comment by plehegar** [comment]
Decision was issued.
