### ISSUE TITLE
[PR request] Resource Timing Level 1

### ISSUE THREAD

**Issue by siusin** [plehegar/transitions#8]
# Document title, URLs, estimated publication date
Resource Timing Level 1
https://www.w3.org/TR/2017/PR-resource-timing-1-20170110/
10 January 2017

# Abstract
This specification defines an interface for web applications to access the complete timing information for resources in a document.

# Status
https://www.w3.org/TR/2017/PR-resource-timing-1-20170110/#sotd

# Link to group's decision to request transition
https://www.w3.org/2016/12/14-webperf-minutes.html#item02

# Changes
No.

# Requirements satisfied
We have met 2+ implementations criteria, please see the Working Group's implementation report (https://w3c.github.io/test-results/resource-timing/all.html) of the major browser vendors.

# Dependencies met (or not)
By publishing this Proposed Recommendation, W3C expects the functionality specified in this Proposed Recommendation will not be affected by changes to High Resolution Time Level 2 (CR) and Web Workers (WD) as these specifications proceed to Recommendation.

# Wide Review
In addition to review by the WebPerf WG and the WebAppSec WG (https://lists.w3.org/Archives/Public/public-webappsec/2016May/0074.html), the spec has multiple implementations including Chrome, Edge, Firefox, and Safari.

# Issues addressed
All issues for Level 1 have been addressed. The current open issues of Resource Timing(https://github.com/w3c/resource-timing/issues) will be resolved in the future versions of the Resource Timing spec.

# Formal Objections
No.

# Implementation
We have 2+ implementations from the major browser venders (Chrome, Edge, and Firefox). 
The failure in test_resource_timing.html is about nextHopProtocol, which is under discussion in Level 2 of this spec.

# Patent disclosures
https://www.w3.org/2004/01/pp-impl/45211/status
No relevant disclosure.

**Comment by siusin** [comment]
@plehegar 
Could you review this draft TransReq please?

**Comment by plehegar** [comment]
Point to https://w3c.github.io/test-results/resource-timing/index.html instead of all.html and ship it.
Thanks.

**Comment by siusin** [comment]
Done! 

https://lists.w3.org/Archives/Member/chairs/2016OctDec/0138.html
